DELETE FROM [dbo].[exCollectionKeyValue]
DELETE FROM [dbo].[exCollectionValue]
DELETE FROM [dbo].[exURLQuery]
DELETE FROM [dbo].[exURL]
DELETE FROM [dbo].[exWebApplication]
DELETE FROM [dbo].[exContextWeb]
DELETE FROM [dbo].[exApplication]
DELETE FROM [dbo].[exTargetSite]
DELETE FROM [dbo].[exInstance]
DELETE FROM [dbo].[exExceptionPolicy]
DELETE FROM [dbo].[exException]
GO
